config/routes.rb
Retailers::Application.routes.draw do
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'search', to: 'search#search', as: 'search'
  resources :users, only: :show do
    resources :friends, only: :index
  end
  root to: 'static_pages#login'

  
  resources :promotion_cards
  resources :promotions do
    resources :images
  end
  
  resources :persons
  resource  :favourites_relations, only: [:create, :destroy]   
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @promotion = Promotion.first
    @promotion = Promotion.new unless @promotion
    if @promotion
      respond_to do |format|
        format.html
        format.json do
          images = @promotion.images
          render :json => images.as_json(:only => :file) and return
        end
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.haml
#home-carousel
  %ul.items
  #pager
:javascript
  HomeCarousel();

app/views/home/index.html.haml
- content_for :header do
  %h3
    = !@promotion.nil? ? image_tag(@promotion.logo.to_s) : "[Promotion Company name]"
  .header_shadow
  %h1 
    = !@promotion.nil? ? @promotion.title : "[Promotion Header]"
  = render :partial => 'carousel'
  .bottom_shadow
.promotion_conditions
  %h2 
    = !@promotion.nil? ? @promotion.desc : "[Promotion conditions]"

.copy Upload this promotion to your card. No need to bring a flyer with you!

#credit_card_shadow
  .credit_card
    #credit_cards_icons
    %span.card_left Register credit/debit card.
    #credit_cards_icon
    = form_for @promotion.promotion_cards.new,  :url => promotion_cards_path  do |f|
      = f.text_field :card_number, placeholder: "Enter Credit or Debit Card Number"
      .submit_button
        = link_to "" , "#"
    = link_to 'Terms of Service', "#"

.how_works
  .one
    .shadow
      .number
      .description Register any credit or debit card.
  .two
    .shadow
      .number
      .description Visit the Store and Shop as you normaly do.
  .three
    .shadow
      .number
      .description The promotion is automatically applied when you make a purchese with your registred card.
   
.bypass
  = link_to_function "No thanks, I'd rather print this promotion and bring it with me.", "javascript:print()"
 