config/routes.rb
Retailers::Application.routes.draw do
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'search', to: 'search#search', as: 'search'
  resources :users, only: :show do
    resources :friends, only: :index
  end
  root to: 'static_pages#login'

  
  resources :promotion_cards
  resources :promotions do
    resources :images
  end
  
  resources :persons
  resource  :favourites_relations, only: [:create, :destroy]   
  

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  attr_accessible :desc, :end_time, :start_time, :title, :company_name, :logo
  mount_uploader :logo, LogoUploader
  has_many :images
  has_many :promotion_cards, :class_name => 'PromotionCards'
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  def index
    @promotions = Promotion.all
  end

  def show
    @promotion = Promotion.find_by_id(params[:id])
    return redirect_to promotions_path if @promotion.nil?
  end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(params[:promotion])
    if @promotion.save
      flash[:notice] = 'Successfuly created'
      redirect_to new_promotion_image_path(@promotion)
      return
    else
      #Check fields for valid
      flash[:error] = 'Something go wrong'
      redirect_to promotions_path
      return
    end
  end

  def destroy
    @promotion = Promotion.find(params[:id])
    if @promotion.destroy
      flash[:notice] = 'Successfuly created'
      redirect_to promotions_path
      return
    else
      flash[:error] = 'Something go wrong'
      redirect_to promotions_path
      return
    end
  end
end

app/views/promotions/index.haml
%h1 Promotions
%table.sample
  %tr
    %th Id
    %th Company Name
    %th Logo
    %th Title
    %th Desc
    %th Start time
    %th End time
  - @promotions.each do |promotion|
    %tr
      %td
        = promotion.id
      %td
        = promotion.company_name
      %td
        = image_tag(promotion.logo.to_s)
      %td 
        = link_to promotion.title, promotion_path(promotion)
      %td 
        = promotion.desc
      %td 
        = promotion.start_time
      %td 
        = promotion.end_time
  = link_to "Create new", new_promotion_path

app/views/promotions/new.haml
= form_for @promotion do |form|
  %label Company Name:
  = form.text_field  :company_name
  %br
  %label Logo:
  = form.file_field  :logo
  %br
  %label Title:
  = form.text_field  :title
  %br
  %label Description:
  %br
  = form.text_area  :desc
  %br
  %label Start Time:
  = form.text_field  :start_time
  %br
  %label End Time:
  = form.text_field  :end_time
  %br
  = submit_tag 'Submit'